### ISSUE TITLE
Compact Dark Versions have light shell menus

### ISSUE THREAD

**Issue by SeineEloquenz** [vinceliuice/Orchis-theme#290]
The `Compact Dark` Versions have light menus in the gnome shell.
On the non-compact versions the styling works fine.
I'm using Gnome 43 with the latest commit of this repo.
This is how it looks:
![image](https://user-images.githubusercontent.com/34923333/212492339-d7c7d5aa-bca7-4885-b4b7-a128506f0465.png)

**Comment by vinceliuice** [comment]
Fixed now

**Comment by stefanocirici** [comment]
I am still facing this issue after the latest update.
On F37 after a clean install of the theme in compact mode, compact tweak and dark colors:
`$ ./install.sh -t default -c dark -s compact --tweaks compact --round 3 -l`
