### ISSUE TITLE
Gnome 44 broke the theme

### ISSUE THREAD

**Issue by MiMillieuh** [vinceliuice/Orchis-theme#309]
Hello,

Since I've updated to Fedora 38 I have some issue with the theme that might be related to the gnome 44 update : 

Here some example : 

Panel has some issue : 

![image](https://user-images.githubusercontent.com/52078885/227620780-616cea57-4e79-4864-ac57-2783857aa546.png)

Window shadow looks weird and offset : 

![image](https://user-images.githubusercontent.com/52078885/227621017-e3485ace-599f-41e9-8a0a-6c24ee13786f.png)

And some app have flickering glitches in some area (only GTK4 apps with libadwaita)

And some window take 30 seconds to appear : 

![image](https://user-images.githubusercontent.com/52078885/227621634-5419f5a7-d4dc-4d97-9f1d-c3810566bb50.png)

Another bug when resizing window : 

![image](https://user-images.githubusercontent.com/52078885/227646189-3c9d66fd-7968-4d11-a427-9d7c575de849.png)

Thanks and have a nice day !

**Comment by vinceliuice** [comment]
Fixed now

**Comment by cxllm** [comment]
I am having this same issue right now and I am not sure what the fix is, I have uninstalled and reinstalled orchis and it has not fixed it, same operating system and bug

**Comment by vinceliuice** [comment]
The quicksetting issue is fixed, not the window issue, this window issue is a gnome issue

**Comment by cxllm** [comment]
Oh, okay, thanks for the info

**Comment by PrzemekSkw** [comment]
Hello, after upgrade I have that window titlebar glitches no matter what theme I use.
![image](https://github.com/vinceliuice/Orchis-theme/assets/25219988/f8bb4c1a-469d-4196-a6d7-247b0c254947)

But gnome windows are OK. I see this only with apps like thinderbird.
Regards.

**Comment by MiMillieuh** [comment]
> Hello, after upgrade I have that window titlebar glitches no matter what theme I use. ![image](https://user-images.githubusercontent.com/25219988/237952639-f8bb4c1a-469d-4196-a6d7-247b0c254947.png)
> 
> But gnome windows are OK. I see this only with apps like thinderbird. Regards.

I can confirm I have it sometimes, it happens only on Xwayland app and it's really not annoying compared to the issue a few weeks ago.

We need to wait for the theme to be updated. these times gnome seems to break a lot of things.
