### ISSUE TITLE
Notification boxes on GNOME 46

### ISSUE THREAD

**Issue by bubner** [vinceliuice/Orchis-theme#412]
Notification boxes on GNOME 46 are also broken, cannot read the text and everything is wide & left aligned
![image](https://github.com/vinceliuice/Orchis-theme/assets/81782264/06248d35-3ae3-4a78-bd51-132b15495ea3)

**Comment by with1874** [comment]
archlinux same +1

**Comment by litianyue0929** [comment]
Adwaita theme is also bug-filled.

**Comment by juanejot** [comment]
Same experience, also on Arch. A web search tells me it seems to be happening with many themes; GNOME likely changed something specifically with notification display in 46 that not only lets them show more info in Adwaita, but screws up how (any, I’d assume!) user theme notifications get formatted.
But yes, Adwaita’s notifications are screwed up all on their own in 46; wish I had a screenshot of a well-(block)-formatted notification with `“<i>[text which should be italicized]</i>”` written at the bottom of it! 😂

**Comment by DowneyX** [comment]
same issue

**Comment by shizhangsz** [comment]
+1

**Comment by vinceliuice** [comment]
Fixed

**Comment by TiagodePAlves** [comment]
Started hitting this issue on Arch Linux with the AUR package ([orchis-theme](https://aur.archlinux.org/packages/orchis-theme)).

<details>
  <summary><b>System Information</b></summary>
  
  ```raw
System:
  Kernel: 6.8.5-arch1-1 arch: x86_64 bits: 64 compiler: gcc v: 13.2.1
  Desktop: GNOME v: 46.0 Distro: Arch Linux
Machine:
  Type: Desktop Mobo: ASRock model: B450M Steel Legend
    serial: <superuser required> UEFI: American Megatrends v: P10.08
    date: 01/19/2024
Battery:
  Device-1: hidpp_battery_0 model: Logitech Wireless Keyboard
    charge: 55% (should be ignored) status: discharging
  Device-2: hidpp_battery_1 model: Logitech Wireless Mouse
    charge: 55% (should be ignored) status: discharging
CPU:
  Info: quad core model: AMD Ryzen 5 1500X bits: 64 type: MT MCP arch: Zen
    rev: 1 cache: L1: 384 KiB L2: 2 MiB L3: 16 MiB
  Speed (MHz): avg: 1523 high: 1550 min/max: 1550/3500 boost: enabled cores:
    1: 1550 2: 1550 3: 1550 4: 1550 5: 1392 6: 1497 7: 1550 8: 1550
    bogomips: 56018
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: NVIDIA GM206 [GeForce GTX 960] vendor: eVga.com. driver: nvidia
    v: 550.67 arch: Maxwell bus-ID: 07:00.0
  Display: wayland server: X.org v: 1.21.1.13 with: Xwayland v: 23.2.6
    compositor: gnome-shell driver: gpu: nvidia,nvidia-nvswitch
    resolution: no compositor data resolution: 1920x1080
  API: EGL v: 1.5 drivers: nvidia,swrast,zink platforms:
    active: gbm,wayland,x11,surfaceless,device inactive: device-1
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 550.67
    glx-v: 1.4 direct-render: yes renderer: NVIDIA GeForce GTX 960/PCIe/SSE2
  API: Vulkan v: 1.3.279 drivers: nvidia surfaces: xcb,xlib,wayland
    devices: 1
Audio:
  Device-1: NVIDIA GM206 High Definition Audio vendor: eVga.com.
    driver: snd_hda_intel v: kernel bus-ID: 07:00.1
  Device-2: AMD Family 17h HD Audio vendor: ASRock driver: snd_hda_intel
    v: kernel bus-ID: 09:00.3
  API: ALSA v: k6.8.5-arch1-1 status: kernel-api
  Server-1: PipeWire v: 1.0.4 status: active
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    vendor: ASRock driver: r8169 v: kernel port: f000 bus-ID: 05:00.0
  IF: enp5s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
Drives:
  Local Storage: total: 465.76 GiB used: 27.01 GiB (5.8%)
  ID-1: /dev/nvme0n1 vendor: Kingston model: SA2000M8500G size: 465.76 GiB
    temp: 35.9 C
Partition:
  ID-1: / size: 453.86 GiB used: 26.74 GiB (5.9%) fs: ext4 dev: /dev/nvme0n1p3
Swap:
  ID-1: swap-1 type: partition size: 8 GiB used: 0 KiB (0.0%)
    dev: /dev/nvme0n1p2
Sensors:
  System Temperatures: cpu: 38.0 C mobo: 37.0 C
  Fan Speeds (rpm): fan-1: 2057 fan-2: 1953 fan-3: 1406 fan-4: 2125
    fan-5: 1090
  Power: 12v: N/A 5v: N/A 3.3v: 3.31 vbat: 3.28
Info:
  Memory: total: 16 GiB available: 15.55 GiB used: 3.6 GiB (23.2%)
  Processes: 285 Uptime: 17m Init: systemd
  Packages: 1128 Compilers: clang: 17.0.6 gcc: 13.2.1 Shell: fish v: 3.7.1
    inxi: 3.3.33
  ```
  
</details>

**Comment by Taijian** [comment]
> Started hitting this issue again on Arch Linux with the AUR package ([orchis-theme 2024_04_01-1](https://aur.archlinux.org/packages/orchis-theme)). Using "Orchis Dark Compact".
> System Information 

I had the same issue with the AUR package. Downloading this archive and the installing via the manual method (install.sh) did work though and the issue went away.

**Comment by TiagodePAlves** [comment]
Yeah, that package uses `realease/Orchis.tar.xz`, which is not always up-to-date. It has been fixed now, but just because the tar release is now pointing to `2024-04-01`, the first one with a fix. I've let a comment in the AUR package about this.

**Comment by ckotte** [comment]
I still have this issue on Arch Linux. I'm using orchis-theme-git from AUR. I updated it a few times since GNOME 46 was installed. I also re-installed it.  So the package should be up-to-date.

How can I check the right notification config? Maybe it uses some old files...!?

**Comment by vinceliuice** [comment]
@ckotte you can  install this theme frome github

**Comment by ckotte** [comment]
I'm using the latest version with commit c8229e3bd5b9d8395c6edc8601308129a1849aae

**Comment by ckotte** [comment]
I installed it manually via:
```
sudo ./install.sh -t default -d "/usr/share/themes"
GNOME Shell 46.1
Installing '/usr/share/themes/Orchis'...
Installing '/usr/share/themes/Orchis-Compact'...
Installing '/usr/share/themes/Orchis-Light'...
Installing '/usr/share/themes/Orchis-Light-Compact'...
Installing '/usr/share/themes/Orchis-Dark'...
Installing '/usr/share/themes/Orchis-Dark-Compact'...

Done.

```
but I still have the problem

![image](https://github.com/vinceliuice/Orchis-theme/assets/8488565/00177f72-d9fe-48c7-a72d-42e7db909f65)

**Comment by vinceliuice** [comment]
Why run it with sudo ?

**Comment by ckotte** [comment]
To install the themes in ```/usr/share/themes```

**Comment by vinceliuice** [comment]
Try Run `./install.sh -r` and ` sudo ./install.sh -r` before you install

**Comment by ckotte** [comment]
@vinceliuice Doesn't work. Still cannot see notifications.
