### ISSUE TITLE
[Gnome 46] Orchis makes Dash to Panel freak out

### ISSUE THREAD

**Issue by Enderteck** [vinceliuice/Orchis-theme#438]
Here's a vid to explain:

https://github.com/vinceliuice/Orchis-theme/assets/123917079/820bdb4f-1892-47c3-b73d-3b768129fd55

This is a pretty weird bug and I tried to change every setting in dash to panel but to no avail. THe solution is to not use orchis as the shell theme (not ideal)

This is pretty annoying though, having you taskbar shift up and down when hovering over apps.

**Comment by vinceliuice** [comment]
This is fixed； https://github.com/vinceliuice/Orchis-theme/issues/437

**Comment by dfkamm** [comment]
I am still seeing this after downloading the latest Orchis release.
